//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibits()
        {
            this.Exhibit_Exhibition = new HashSet<Exhibit_Exhibition>();
        }
    
        public int Id_Exhibit { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> Id_Author { get; set; }
        public Nullable<int> Id_Condition { get; set; }
        public Nullable<int> Id_Type { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Conditions Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exhibit_Exhibition> Exhibit_Exhibition { get; set; }
        public virtual Types Types { get; set; }
    }
}
