//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musem.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class МузейEntities11 : DbContext
    {
        public МузейEntities11()
            : base("name=МузейEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Conditions> Conditions { get; set; }
        public virtual DbSet<Curator> Curator { get; set; }
        public virtual DbSet<Curator_Exhibition> Curator_Exhibition { get; set; }
        public virtual DbSet<Exhibit_Exhibition> Exhibit_Exhibition { get; set; }
        public virtual DbSet<Exhibitions> Exhibitions { get; set; }
        public virtual DbSet<Exhibits> Exhibits { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
