//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id_Report { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> VisitorCount { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<int> Id_Exhibition { get; set; }
    
        public virtual Exhibitions Exhibitions { get; set; }
    }
}
