//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id_Ticket { get; set; }
        public Nullable<int> Id_Exhibition { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual Exhibitions Exhibitions { get; set; }
        public virtual User User { get; set; }
    }
}
